[etcd]
name = "etcd-1"
data_dir = "data"
wal_dir = "data/wal"
prevote = true
peers = "etcd-1=http://0.0.0.0:2380,etcd-2=http://0.0.0.0:2480,etcd-3=http://0.0.0.0:2580"
raft_addr = "http://0.0.0.0:2380"
client_addr = "http://localhost:2379"
client_timeout = 3

[server]
addr = "0.0.0.0:1080"
log_file = "metaserver.log"
enable_heartbeat_checker = false
pprof_addr = "0.0.0.0:6063"
log_level = "info"